Define Field to preprocess raw data

In [1]:
import torch
from torchtext.datasets import IMDB
train_iter = IMDB(split='train')

In [2]:
next(train_iter)

('neg',
 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far be

In [3]:
from torchtext.data.utils import get_tokenizer
from collections import Counter
from torchtext.vocab import Vocab

tokenizer = get_tokenizer('basic_english')
counter = Counter()
for (label, line) in train_iter:
    counter.update(tokenizer(line))
vocab = Vocab(counter, min_freq=1, 
              max_size = 25000, 
              vectors = "glove.6B.100d", 
              unk_init = torch.Tensor.normal_)

In [4]:
vocab.freqs.most_common(20)

[('the', 335736),
 ('.', 327178),
 (',', 276269),
 ('and', 163282),
 ('a', 162468),
 ('of', 145431),
 ('to', 135199),
 ("'", 133855),
 ('is', 107217),
 ('it', 96018),
 ('in', 93297),
 ('i', 87394),
 ('this', 75874),
 ('that', 73149),
 ('s', 62931),
 ('was', 48167),
 ('as', 46806),
 ('for', 44112),
 ('with', 44040),
 ('movie', 43421)]

In [5]:
text_pipeline = lambda x: [vocab[token] for token in tokenizer(x)]
label_pipeline = lambda x: 0 if x=='neg' else 1

In [71]:
from torch.utils.data import DataLoader
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def collate_batch(batch):
    label_list, text_list, offsets = [], [], [0]
    for (_label, _text) in batch:
         label_list.append(label_pipeline(_label))
         processed_text = torch.tensor(text_pipeline(_text), dtype=torch.int64)
         text_list.append(processed_text)
         offsets.append(processed_text.size(0))
    label_list = torch.tensor(label_list, dtype=torch.int64)
    offsets = torch.tensor(offsets[:-1]).cumsum(dim=0)
    text_list = torch.cat(text_list)
    return label_list.to(device), text_list.to(device), offsets.to(device)

train_iter = IMDB(split='train')
dataloader = DataLoader(train_iter, batch_size=8, shuffle=False, collate_fn=collate_batch)

In [72]:
for idx, (label, text, offsets) in enumerate(dataloader):
    print(text.shape)
    print(label)

torch.Size([1805])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2298])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2387])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1764])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1900])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2530])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2432])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1702])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2240])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1800])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([3041])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2914])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2056])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1860])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1950])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1639])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2486])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2149])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1956])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([

torch.Size([1894])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2235])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2577])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2181])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2404])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1372])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1865])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2297])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2797])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2646])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1503])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2553])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1289])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1714])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2304])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2044])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([4084])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2030])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2164])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([

torch.Size([1645])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2398])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1588])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1788])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2265])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2426])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1653])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1703])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2561])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([3311])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1472])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2799])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2191])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2977])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([6258])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1914])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2032])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2017])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1352])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([

torch.Size([1938])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2922])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2539])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2129])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2917])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1680])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2233])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2230])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([3493])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1561])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2347])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1825])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1792])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1992])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2836])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2178])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2030])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1400])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([823])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2

torch.Size([2450])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2350])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1969])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1625])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1660])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2406])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2295])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1793])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1925])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2406])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1406])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1732])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1963])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1447])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1856])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1688])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1990])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1597])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1295])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([

torch.Size([3218])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2674])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([3210])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([3816])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([3385])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1468])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2241])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1635])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2649])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2432])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1896])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2263])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2657])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2012])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2042])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2712])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([3180])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1560])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1969])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([

torch.Size([2851])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1837])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([3276])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([4582])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1777])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2083])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2529])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1944])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2611])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1747])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1392])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2375])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2615])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2508])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2059])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2257])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2144])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1298])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2700])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([

torch.Size([3179])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2203])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1801])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1492])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1355])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1666])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1957])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1894])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2260])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2686])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2390])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2090])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2862])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1333])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1371])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2267])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([3132])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1329])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1285])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([

tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1837])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2092])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1994])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1086])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2410])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2574])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2284])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2360])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([3079])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2679])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1743])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([3474])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2078])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1305])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1613])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1817])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1481])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([2472])
tensor([0, 0, 0, 0, 0, 0, 0, 0])
torch.Size([1757])
tensor([0, 0

torch.Size([2640])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2608])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1632])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2878])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1777])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1057])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1118])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1336])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1374])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1357])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1437])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2904])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1484])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1485])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2067])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1702])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1945])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2944])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3430])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([

torch.Size([2009])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1752])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1797])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2298])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1817])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1576])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1823])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2873])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([797])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1496])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3287])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1865])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1258])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1652])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1763])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1069])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2945])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2855])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1156])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2

torch.Size([2534])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1086])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1903])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([903])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2586])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2171])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1749])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2347])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3050])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1758])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3362])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2725])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3510])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3273])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3249])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1306])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2759])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2242])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([772])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([11

torch.Size([2180])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3259])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2848])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2251])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1909])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1786])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2236])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1968])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2362])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2735])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1599])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2781])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2592])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3367])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2855])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3883])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1406])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1248])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1233])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([

torch.Size([1869])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2205])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2539])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([836])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1584])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3385])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3793])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2892])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2113])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3725])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3372])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1933])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1648])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2273])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2825])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1906])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2225])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3263])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1978])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2

torch.Size([2261])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1293])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1149])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2869])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2695])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2409])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3713])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3463])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([4327])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1252])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2439])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2727])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1171])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1867])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1428])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2824])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1639])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2052])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1840])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([

torch.Size([1908])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3525])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3641])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2788])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1079])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2127])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2878])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3597])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1895])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1600])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1444])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2241])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1061])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1212])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2549])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2462])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2101])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3507])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1227])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([

torch.Size([2691])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1847])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1985])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1685])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1903])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1986])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2450])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2294])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1363])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2806])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1450])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1531])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2478])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3978])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3230])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2184])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2329])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3192])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1797])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([

torch.Size([3631])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3036])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2385])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2980])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1798])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2625])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2184])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1814])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2940])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3279])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([3010])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2087])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1639])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1805])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1677])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2594])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([2384])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1072])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([1868])
tensor([1, 1, 1, 1, 1, 1, 1, 1])
torch.Size([

Define model

In [8]:
from torch import nn

class TextClassificationModel(nn.Module):

    def __init__(self, vocab_size, embed_dim, num_class):
        super(TextClassificationModel, self).__init__()
        self.embedding = nn.EmbeddingBag(vocab_size, embed_dim, sparse=True)
        self.fc = nn.Linear(embed_dim, num_class)
        self.init_weights()

    def init_weights(self):
        initrange = 0.5
        self.embedding.weight.data.uniform_(-initrange, initrange)
        self.fc.weight.data.uniform_(-initrange, initrange)
        self.fc.bias.data.zero_()

    def forward(self, text, offsets):
        embedded = self.embedding(text, offsets)
        return self.fc(embedded)

In [66]:
num_class = 2
vocab_size = len(vocab)
emsize = 64
model = TextClassificationModel(vocab_size, emsize, num_class).to(device)

Define dataloader

In [67]:
import time

def train(dataloader):
    model.train()
    total_acc, total_count = 0, 0
    log_interval = 500
    start_time = time.time()

    for idx, (label, text, offsets) in enumerate(dataloader):
        optimizer.zero_grad()
        predited_label = model(text, offsets)
        loss = criterion(predited_label, label)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 0.1)
        optimizer.step()
        total_acc += (predited_label.argmax(1) == label).sum().item()
        total_count += label.size(0)
        if idx % log_interval == 0 and idx > 0:
            elapsed = time.time() - start_time
            print('| epoch {:3d} | {:5d}/{:5d} batches '
                  '| accuracy {:8.3f}'.format(epoch, idx, len(dataloader),
                                              total_acc/total_count))
            total_acc, total_count = 0, 0
            start_time = time.time()

def evaluate(dataloader):
    model.eval()
    total_acc, total_count = 0, 0

    with torch.no_grad():
        for idx, (label, text, offsets) in enumerate(dataloader):
            predited_label = model(text, offsets)
            loss = criterion(predited_label, label)
            total_acc += (predited_label.argmax(1) == label).sum().item()
            total_count += label.size(0)
    return total_acc/total_count

In [68]:
from torch.utils.data.dataset import random_split
# Hyperparameters
EPOCHS = 10 # epoch
LR = 5  # learning rate
BATCH_SIZE = 64 # batch size for training

criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=LR)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, 1.0, gamma=0.1)
total_accu = None
train_iter, test_iter = IMDB()
train_dataset = list(train_iter)
test_dataset = list(test_iter)
num_train = int(len(train_dataset) * 0.95)
split_train_, split_valid_ = \
    random_split(train_dataset, [num_train, len(train_dataset) - num_train])

train_dataloader = DataLoader(split_train_, batch_size=BATCH_SIZE,
                              shuffle=True, collate_fn=collate_batch)
valid_dataloader = DataLoader(split_valid_, batch_size=BATCH_SIZE,
                              shuffle=True, collate_fn=collate_batch)
test_dataloader = DataLoader(test_dataset, batch_size=BATCH_SIZE,
                             shuffle=True, collate_fn=collate_batch)

for epoch in range(1, EPOCHS + 1):
    epoch_start_time = time.time()
    train(train_dataloader)
    accu_val = evaluate(valid_dataloader)
    if total_accu is not None and total_accu > accu_val:
      scheduler.step()
    else:
       total_accu = accu_val
    print('-' * 59)
    print('| end of epoch {:3d} | time: {:5.2f}s | '
          'valid accuracy {:8.3f} '.format(epoch,
                                           time.time() - epoch_start_time,
                                           accu_val))
    print('-' * 59)

torch.Size([64, 64])


RuntimeError: input must have 3 dimensions, got 2

Evaluation

In [13]:
print('Checking the results of test dataset.')
accu_test = evaluate(test_dataloader)
print('test accuracy {:8.3f}'.format(accu_test))

Checking the results of test dataset.
test accuracy    0.853


Predict on a single instance

In [35]:
ag_news_label = {0: "negative",
                 1: "positive"}

def predict(text, text_pipeline):
    with torch.no_grad():
        text = torch.tensor(text_pipeline(text))
        output = model(text, torch.tensor([0]))
        print(output)
        return output.argmax(1).item()


model = model.to("cpu")

In [47]:
ex_text_str = "It was a wonderful educational short journey into the deep blue searching for the king,\
the great white shark , me and my family were fully enjoyed watching this beautiful movie and we were \
fascinated by the magnificent clear blue color under water and the great camera work , unfortunately it\
was too short (only 40 minutes), like we say in Arabic ( happy times passes fast) , but it's really worth our time."

print("This is a %s review" %ag_news_label[predict(ex_text_str, text_pipeline)])

tensor([[-2.7194,  2.3986]])
This is a positive review
